description = "Railway builder based off the Paketo full builder. Support for NodeJS, Go, DotNet, HTTPD, Java, Nginx, PHP, Ruby, Python"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/nginx:0.5.2"
  version = "0.5.2"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/php:0.8.0"
  version = "0.8.0"

[stack]
  build-image = "docker.io/paketobuildpacks/build:1.3.13-full-cnb"
  id = "io.buildpacks.stacks.bionic"
  run-image = "index.docker.io/paketobuildpacks/run:full-cnb"
  run-image-mirrors = ["gcr.io/paketo-buildpacks/run:full-cnb"]
